# 中等数据集配置
experiment_name: "medium_dataset"
batch_size: 2
learning_rate: 0.00005
weight_decay: 0.0001
grad_clip: 0.5
num_epochs: 50
save_every: 10
hidden_dim: 128
encoder_layers: 2
decoder_layers: 2
dropout: 0.3
max_patience: 20
label_smoothing: 0.1
validation_split: 0.2

# 数据配置
audio_dir: "data/audio"
labels_file: "data/labels.csv"
device: "auto"
num_workers: 0
pin_memory: true
shuffle: true
random_seed: 42

# 日志配置
log_level: "INFO"
tensorboard_log_dir: "experiments/runs"
checkpoint_dir: "experiments/checkpoints"
log_dir: "experiments/logs"

# 音频处理配置
sample_rate: 48000
n_fft: 1024
hop_length: 512
max_length: 200
